export const SLICE_RULES = {
  weights: {
    Speed: 10.0,
    "Offense%": 8.5,
    "Health%": 8.0,
    "Protection%": 8.0,
    "Tenacity%": 7.5,
    "Potency%": 7.5,
    "Defense%": 5.0,
    "Crit Chance%": 4.5,
    // Flat stats: much weaker than % equivalents — scored low so % always wins
    Offense: 2.0,
    Health: 1.5,
    Protection: 1.5,
    Defense: 1.0,
    "Accuracy%": 2.5,
    "Crit Avoidance%": 2.0,
  },
  priorityMultipliers: [1.0, 0.82, 0.64, 0.46],
  nonPriorityMultiplier: 0.7,
  fitWeights: {
    primaryBuildMainSet: 1.0,
    alternateBuildMainSet: 0.9,
    primaryBuildSideSet: 0.8,
    alternateBuildSideSet: 0.72,
    primaryBuildShell: 0.88,
    alternateBuildShell: 0.78,
  },
  profileMultipliers: {
    attacker: {
      Speed: 1.2,
      "Offense%": 1.35,
      Offense: 1.2,
      "Crit Chance%": 1.1,
      "Health%": 0.9,
      "Protection%": 0.9,
      "Potency%": 0.85,
      "Tenacity%": 0.85,
    },
    support: {
      Speed: 1.45,
      "Potency%": 1.25,
      "Tenacity%": 1.15,
      "Protection%": 1.1,
      "Health%": 1.05,
      "Offense%": 0.75,
      Offense: 0.7,
      "Crit Chance%": 0.6,
    },
    tank: {
      Speed: 1.0,
      "Health%": 1.3,
      "Protection%": 1.3,
      "Defense%": 1.2,
      Defense: 1.1,
      "Tenacity%": 1.15,
      "Offense%": 0.65,
      "Crit Chance%": 0.4,
    },
    healer: {
      Speed: 1.25,
      "Health%": 1.25,
      "Protection%": 1.1,
      "Tenacity%": 1.1,
      "Potency%": 0.95,
      "Offense%": 0.65,
    },
    leader: {
      Speed: 1.2,
      "Health%": 1.1,
      "Protection%": 1.1,
      "Offense%": 1.0,
      "Tenacity%": 1.0,
    },
    bruiser: {
      "Health%": 1.4,
      "Tenacity%": 1.3,
      Speed: 1.0,
      "Protection%": 0.8,
      "Defense%": 1.1,
      "Offense%": 0.9,
    },
    debuffer: {
      "Potency%": 1.4,
      Speed: 1.25,
      "Tenacity%": 1.0,
      "Protection%": 1.0,
      "Health%": 1.0,
      "Offense%": 0.7,
    },
  },
  synergyBonuses: [
    { stats: ["Speed", "Potency%"], tags: ["support", "debuffer"], bonus: 4 },
    { stats: ["Speed", "Tenacity%"], tags: ["tank", "support", "bruiser"], bonus: 4 },
    { stats: ["Speed", "Offense%"], tags: ["attacker"], bonus: 4 },
    { stats: ["Health%", "Tenacity%"], tags: ["tank", "bruiser"], bonus: 4 },
    { stats: ["Protection%", "Defense%"], tags: ["tank"], bonus: 4 },
    { stats: ["Offense", "Offense%"], tags: ["attacker"], bonus: 3 },
    { stats: ["Health", "Health%"], tags: ["tank", "bruiser", "healer"], bonus: 3 },
    { stats: ["Protection", "Protection%"], tags: ["tank", "support"], bonus: 3 },
  ],
  scoreWeights: {
    fit: 0.35,
    secondaries: 0.4,
    upside: 0.15,
    context: 0.1,
  },
  thresholds: [
    { min: 90, label: "PREMIUM SLICE" },
    { min: 80, label: "STRONG SLICE" },
    { min: 68, label: "SLICE IF NEEDED" },
    { min: 60, label: "HOLD" },
    { min: 30, label: "FILLER ONLY" },
    { min: 0,  label: "SELL" },
  ],
  // Flat base stats (Speed excluded — flat Speed is the most valuable secondary)
  flatStats: new Set(["Offense", "Health", "Protection", "Defense"]),
  flatStatSellThreshold: 3, // 3+ flat stats = auto-sell regardless of score
};
